[tool.vulture]
exclude = [".venv/", "test*/"]
# ignore_decorators = ["@app.route", "@require_*"]
# ignore_names = ["visit_*", "do_*"]
make_whitelist = true
min_confidence = 80
paths = ["C:\\Users\\alt\\devel\\dpse_minimal\\am-core-python",
        	"C:\\Users\\alt\\devel\\dpse_minimal\\am-robots-python",
            "C:\\Users\\alt\\devel\\dpse_minimal\\lar-utils",
            "C:\\Users\\alt\\devel\\dpse_minimal\\meta-learning-experiments",
            "C:\\Users\\alt\\devel\\dpse_minimal\\nn-visualization",
            "C:\\Users\\alt\\devel\\dpse_minimal\\pytorch-utils",
            "C:\\Users\\alt\\devel\\dpse_minimal\\spi-api",
            "C:\\Users\\alt\\devel\\dpse_minimal\\spi-core",
            "C:\\Users\\alt\\devel\\dpse_minimal\\urdfpy"]
sort_by_size = true
# verbose = true